import { useState } from 'react'
import { Cloud, Database, Moon, Sun, WifiOff, CheckCircle2, AlertTriangle } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { useAppStore } from '@/app/store'
import { isFirebaseConfigured } from '@/infrastructure/persistence/firebase/client'
import { toast } from 'sonner'
export function SettingsPage(){const {profile,setProfile,theme,setTheme,sync}=useAppStore();const [name,setName]=useState(profile.name),[target,setTarget]=useState(String(profile.targetWeightKg));const save=async()=>{await setProfile({...profile,name:name.trim()||profile.name,targetWeightKg:Number(target)||profile.targetWeightKg});toast.success('Settings saved')};const online=typeof navigator==='undefined'||navigator.onLine;return <div className="page-stack long-page"><section className="page-heading"><div><p className="eyebrow">System</p><h1>Settings</h1><p className="subtle">Your preferences and storage state stay separate from activity history.</p></div></section><Card><CardContent><div className="card-kicker">Profile & target</div><div className="form-grid settings-grid"><label className="field-label">Name<Input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field-label">Target weight (kg)<Input type="number" min="1" value={target} onChange={e=>setTarget(e.target.value)}/></label></div><Button onClick={save}>Save settings</Button></CardContent></Card><Card><CardContent><div className="card-kicker">Appearance</div><div className="appearance-row"><button className={theme==='system'?'selected':''} onClick={()=>setTheme('system')}><Moon size={16}/> System</button><button className={theme==='light'?'selected':''} onClick={()=>setTheme('light')}><Sun size={16}/> Light</button><button className={theme==='dark'?'selected':''} onClick={()=>setTheme('dark')}><Moon size={16}/> Dark</button></div></CardContent></Card><div className="two-col"><Card><CardContent><Database size={18}/><h3>Local storage</h3><p>Validated writes are committed to IndexedDB first. Activity remains available offline and sync work is queued locally.</p><div className="system-status"><CheckCircle2 size={14}/><span>{sync.pending} pending · {sync.failed} failed</span></div></CardContent></Card><Card><CardContent>{online?<Cloud size={18}/>:<WifiOff size={18}/>}<h3>Cloud sync</h3><p>{isFirebaseConfigured()?'Firebase is configured. Sync runs in the background when a connection is available.':'Firebase is not configured yet. The app remains fully usable locally.'}</p><div className={`system-status ${sync.failed?'warning':''}`}>{sync.failed?<AlertTriangle size={14}/>:<CheckCircle2 size={14}/>}<span>{sync.lastError|| (sync.lastSyncedAt?`Last sync ${new Date(sync.lastSyncedAt).toLocaleString()}`:'No cloud sync yet')}</span></div></CardContent></Card></div></div>}
